-- MySQL Script generated by MySQL Workbench
-- Tue Oct 30 04:04:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemaactivos
-- -----------------------------------------------------
drop database if exists sistemaactivos;
-- -----------------------------------------------------
-- Schema sistemaactivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaactivos` DEFAULT CHARACTER SET utf8 ;
USE `sistemaactivos` ;

-- -----------------------------------------------------
-- Table `sistemaactivos`.`Activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Activo` (
  `codigoId` VARCHAR(45) NOT NULL,
  `labAct` INT(11) NULL DEFAULT NULL,
  `bien_ID` INT(11) NOT NULL,
  PRIMARY KEY (`codigoId`),
  INDEX `Activo_Labor` (`labAct` ASC),
  INDEX `fk_activo_bien1_idx` (`bien_ID` ASC),
  CONSTRAINT `llave_LaborA`
    FOREIGN KEY (`labAct`)
    REFERENCES `sistemaactivos`.`labor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activo_bien1`
    FOREIGN KEY (`bien_ID`)
    REFERENCES `sistemaactivos`.`bien` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Bien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Bien` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `serial` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `precioU` DOUBLE NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `solicitud` INT(11) NOT NULL,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Bien_Solicitud` (`solicitud` ASC),
  INDEX `Bien_Categoria` (`categoria` ASC),
  CONSTRAINT `llave_CategoriaB`
    FOREIGN KEY (`categoria`)
    REFERENCES `sistemaactivos`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `llave_SolicitudB`
    FOREIGN KEY (`solicitud`)
    REFERENCES `sistemaactivos`.`solicitud` (`numsol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Categoria` (
  `id` VARCHAR(45) NOT NULL,
  `incremento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Dependencia` (
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Funcionario` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Labor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Labor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcLab` VARCHAR(45) NOT NULL,
  `depLab` VARCHAR(45) NOT NULL,
  `pueLab` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Labor_Funcionario` (`funcLab` ASC),
  INDEX `Labor_Dependencia` (`depLab` ASC),
  INDEX `Labor_Puesto` (`pueLab` ASC),
  CONSTRAINT `llave_FuncionarioL`
    FOREIGN KEY (`funcLab`)
    REFERENCES `sistemaactivos`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `llave_DependenciaL`
    FOREIGN KEY (`depLab`)
    REFERENCES `sistemaactivos`.`Dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `llave_PuestoL`
    FOREIGN KEY (`pueLab`)
    REFERENCES `sistemaactivos`.`Puesto` (`codgo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Puesto` (
  `codgo` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codgo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Solicitud` (
  `numsol` INT NOT NULL AUTO_INCREMENT,
  `numcomp` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantbien` INT NOT NULL,
  `montotal` DOUBLE NOT NULL,
  `razonR` VARCHAR(80) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `registrador` VARCHAR(45) NULL,
  `Dependencia_codigo` VARCHAR(45) NOT NULL,
  `tipoadq` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numsol`),
  INDEX `Solicitud_Funcionario` (`registrador` ASC),
  INDEX `Solicitud_Dependencia` (`Dependencia_codigo` ASC),
  CONSTRAINT `llave_FuncionarioS`
    FOREIGN KEY (`registrador`)
    REFERENCES `sistemaactivos`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `llave_DependenciaS`
    FOREIGN KEY (`Dependencia_codigo`)
    REFERENCES `sistemaactivos`.`Dependencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaactivos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Usuario` (
  `id` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(256) NOT NULL,
  `labUsu` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Usuario_Labor` (`labUsu` ASC),
  CONSTRAINT `llave_LaborU`
    FOREIGN KEY (`labUsu`)
    REFERENCES `sistemaactivos`.`Labor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `sistemaactivos`.`Grupos` (
  `id` VARCHAR(45) NOT NULL,
  `grupo` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
